### ISSUE TITLE
Problems following planarian notebook

### ISSUE THREAD

**Issue by ElHirad** [amisios/Planaria_lineage#3]
Hi. I was trying to reproduce the results in the preprocessing planarian notebook until I got this:
>>> sc.pl.paga_compare(adata, title='100% of data, tSNE and abstracted graph', **paga_plot_params, save='_100percent')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/scanpy/plotting/tools/paga.py", line 127, in paga_compare
    **paga_graph_params)
  File "/usr/local/lib/python3.7/dist-packages/scanpy/plotting/tools/paga.py", line 423, in paga
    if root in node_labels:
NameError: name 'node_labels' is not defined

What should I do?

**Comment by falexwolf** [comment]
Sorry about this. Either run this it with the version of Scanpy that is shown in the notebook, or better, go to the updated notebook on: https://github.com/theislab/paga.

**Comment by ElHirad** [comment]
It didn't fix. I encountered other errors while downloading and installing the other versions of the package. Also, the notebooks on https://github.com/theislab/paga had that problem, too.

**Comment by DuaaAlawad** [comment]
still have the same issue... Can you please help us?
